### ISSUE TITLE
想提个建议

### ISSUE THREAD

**Issue by 970844297** [Sun45/warbanner#2]
希望可以将消息提醒往上挪一点，现在跳出来会挡住最下面的3个按键。虽然也能按到，但感觉蛮不舒服的。
![S20727-10574856](https://user-images.githubusercontent.com/49755767/181151185-6588e3f7-dff6-4000-bfb7-68cbc3672b97.png)

第二个小建议，希望可以整个开关，可以进入APP自动更新作业，有时候第二天忘记更新作业。。
谢谢大佬

**Comment by Sun45** [comment]
感谢使用反馈。
第一条，这是android的消息提示，作业下载完需要处理数据库和界面，是一种保护机制，感觉碍事我可以把显示时间改短
第二条，自动作业更新的话不管是每天第一次打开自动更新还是每次打开都更新，都不能保证作业是最新的，因为作业网一直有人在提交作业，特别是会战前几天作业更新频繁，最后几天肯定没什么更新，这样自动更新的功能就很有局限性，而且有的时候是不需要去自动更新的，比如说后面几天只需要继续使用前面收藏的分刀，或者网站出bug了不能更新。当然也不能改成实时获取的方式，这会影响分刀的速度。
有什么想法或者别的问题可以继续找我。

**Comment by 970844297** [comment]
感谢回复。
第二个建议也许可以搞个“每天(不一定是0点)首次打开时自动更新作业”的开关？是否有必要还是大佬做决定就好，谢谢

**Comment by Sun45** [comment]
就像我说的，不管是每天第一次打开自动更新还是每次打开都更新，都不能保证作业是最新的，做这么一个不一定管用的开关，用户面临的问题就是开还是不开，好像开不开都没什么区别，想保持最新的话一定要手动更新，那这个功能就可有可无了，要是有什么别的方案可以再跟我说。

**Comment by 970844297** [comment]
明白了，感谢回复
