### ISSUE TITLE
关于连点器角色顺序的问题

### ISSUE THREAD

**Issue by Destiny4073** [Sun45/warbanner#3]
通常来说，大多数玩家都是按照角色站位来确定1、2、3、4、5号位，但是连点器是反过来的，感觉非常的反直觉，下意识的就会按错，希望能把角色顺序修改一下。
![20230306204052](https://user-images.githubusercontent.com/79623851/223113520-16839a99-22f3-4616-963d-9c6b01dcab32.png)

**Comment by Sun45** [comment]
确实角色的站位顺序是从右至左的，但是我做的时候遵循的是一般的由上至下由左至右的顺序，谢谢，但是我觉得影响不大，而且过段时间等国服时装官方连点器我就会把这部分功能删掉了
