### ISSUE TITLE
[BUG] 更新数据失败，详情请参考日志

### ISSUE THREAD

**Issue by sgpublic** [Sun45/warbanner#5]
机型：Redmi K20 Pro
系统版本：MIUI 12.5.6.0/Android 11
版本：v3.7.2
日志：
```
08:17:30
getTeamData result is empty
```
复现步骤：
1. 全新安装 v3.7.2
2. 启动，自动下载数据，更新数据失败。
3. 菜单 -> 数据更新，更新数据失败。

补充：
挂了梯子也不行。

**Comment by Sun45** [comment]
作业数据还没更新，等会战开始有作业再更新就行

**Comment by sgpublic** [comment]
> 作业数据还没更新，等会战开始有作业再更新就行

可是这样的话角色数据也下载不下来，想提前把角色筛选搞好，这里是不是可以优化一手（弱弱的

**Comment by Sun45** [comment]
多谢反馈，数据库下载流程确实是这么设计的，看了下，加载部分的问题，改了下，现在应该可以了

**Comment by sgpublic** [comment]
没问题了 👍
